name: Build Android AAB

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build web assets
      run: npm run build
      
    - name: Sync Capacitor
      run: npx cap sync android
      
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      
    - name: Accept Android licenses
      run: yes | sdkmanager --licenses
      
    - name: Install Android SDK components
      run: |
        sdkmanager "platform-tools" "platforms;android-35" "build-tools;35.0.1"
        
    - name: Fix SDK path configuration
      run: |
        rm -f android/local.properties
        echo "sdk.dir=$ANDROID_SDK_ROOT" > android/local.properties
        
    - name: Create keystore from secret
      run: |
        echo "${{ secrets.ANDROID_KEYSTORE_BASE64 }}" | base64 -d > android/app/pingjob-upload-keystore.jks
        
    - name: Create key.properties
      run: |
        echo "storePassword=${{ secrets.ANDROID_KEYSTORE_PASSWORD }}" > android/key.properties
        echo "keyPassword=${{ secrets.ANDROID_KEY_PASSWORD }}" >> android/key.properties
        echo "keyAlias=${{ secrets.ANDROID_KEY_ALIAS }}" >> android/key.properties
        echo "storeFile=pingjob-upload-keystore.jks" >> android/key.properties
        
    - name: Build AAB
      run: |
        cd android
        ./gradlew bundleRelease
        
    - name: Upload AAB artifact
      uses: actions/upload-artifact@v4
      with:
        name: PingJob-v2.0.4-release
        path: android/app/build/outputs/bundle/release/app-release.aab
        retention-days: 30